USE [TeamXCDB]
GO

INSERT INTO Course([name])
VALUES
	('Detweiller Park'),
	('Greene Valley'),
	('Van Horn Woods'),
	('Channahon Park'),
	('Berens Park'),
	('Deer Grove East Forest Preserve'),
	('Minooka HS'),
	('Dellwood Park'),
	('Naperville North HS'),
	('Willow Stream Park'),
	('Hammel Woods'),
	('Lyons Township HS'),
	('Midlothian Meadows'),
	('Hammel Woods (3x1-mile)'),
	('KLM Park'),
	('Hoover Park'),
	('Kress Creek Farms Park'),
	('Stuart Sports Complex'),
	('Springbrook Prarie Forest Preserve'),
	('Plainfield Central HS'),
	('East End Park'),
	('Lincoln Park'),
	('Lewis University'),
	('FFA Farm'),
	('Commissioner''s Park'),
	('Oswego East XC Course'),
	('Catlin Park'),
	('DuPage River Park'),
	('Plainfield East HS'),
	('Sterling Woodlawn Course'),
	('Eaton Preserve'),
	('Morris HS'),
	('Leroy Oakes Forest Preserve'),
	('Sandwich Course'),
	('Lisle Community Park'),
	('ICC XC Course'),
	('Home Course'),
	('Yorkville XC Course'),
	('Maxwell Park'),
	('Three Sisters Park')
